### ISSUE TITLE
error in textfields 

### ISSUE THREAD

**Issue by Belalm** [IcaliaLabs/LoginKit#1]
The text fields are returning empty string in all views:
Signup with: name =  email = password = 
Login with: email = password =

**Comment by danlozano** [comment]
Hmmm that's interesting.

I just checked the example project, to double check, and it is working.

Could I have more info about your code or project?

Thanks!

**Comment by danlozano** [comment]
<img width="1710" alt="screen shot 2017-04-05 at 9 33 43 am" src="https://cloud.githubusercontent.com/assets/2406956/24710562/1c3e8a8a-19e3-11e7-8d81-60f664594b0c.png">
