### ISSUE TITLE
Ios 11 closing view cause crash

### ISSUE THREAD

**Issue by boardmain** [IcaliaLabs/LoginKit#12]
hi, closing all view
make the app crash

the view are nulled on close and if i try to open again the view it crash (nulled view)

i need to comment all
navigationController = nil
        initialViewController = nil
        loginViewController = nil
        signupViewController = nil
        passwordViewController = nil

**Comment by Ahmedshubber** [comment]
@boardmain @rafaelcr @edolopez @kurenn @thelastinuit +1 I have this problem too. If I delete the lines of code that boardmain said above, and I close the loginpage and go back to the view, the text I had before in the textfields is still there. Theres a bug in the code above. Can you do something to solve it because I cant release my app until this bug is fixed so that users can login.

**Comment by danlozano** [comment]
I will look into this later today.

Can you please provide some sample code. 

When does this happen? What part of the code has the crash?

**Comment by jackpaster** [comment]
@danlozano Its the part where your setting the view nil. the code is this. The code is in the login coordinator swift file

> navigationController = nil
initialViewController = nil
loginViewController = nil
signupViewController = nil
passwordViewController = nil

**Comment by rafaelcr** [comment]
@jackpaster can you paste the stack trace of the crash? That would be helpful to @danlozano

**Comment by danlozano** [comment]
Figured out the problem.

Optional (or in my case, implicitly unwrapped optionals) lazy variables are not supported anymore in Swift 4.

Have to figure out a another way to reset the view controllers.

Will have a new version out tonight.

**Comment by danlozano** [comment]
version 0.1.3 is out

should fix this and other swift4 bugs

if anything else comes up open a new issue please

thanks!

**Comment by jackpaster** [comment]
@danlozano I tried it and it doesn't work. I get this error "fatal error: unexpectedly found nil while unwrapping an Optional value" at this line 

> 

     func goToLogin() {
        navigationController.pushViewController(loginViewController, animated: true)
    }

> 

Try pressing login button, go back, press sign up button, go back and press login button again. It doesn't work.

**Comment by jackpaster** [comment]
@danlozano It crashes again and again and its because were setting the view to nil and Xcode doesn't like that. Its unwrapping a nil view before the view even loaded.
