### ISSUE TITLE
Keyboard mover doesn't work

### ISSUE THREAD

**Issue by jackpaster** [IcaliaLabs/LoginKit#15]
@danlozano Hello, thanks for making this repository its great. Theres just one problem. The keyboard mover doesn't move when you switch textfields. Like lets say you go and create an account and click the fist textfield and click next and next, the view doesn't move above the keyboard and the textfield is stuck beneath the keyboard. The same is for login. You click on username and the contine button is stuck beneath the keyboard. Could you fix this in a new update so that all three views(password, signup, and login work for all screen sizes when the keyboard is up). Thanks.

**Comment by jackpaster** [comment]
@rafaelcr @edolopez @kurenn @thelastinuit @joseantoniordlmc Could you check it out.

**Comment by jackpaster** [comment]
I have to release an update for my app but the login keyboard isn't working. Could you please check it out.

**Comment by danlozano** [comment]
Fixed. Will be out in new release today.
