### ISSUE TITLE
LoginCoordinator can't performSegue

### ISSUE THREAD

**Issue by Maryom** [IcaliaLabs/LoginKit#2]
Hi,

Thanks for your repo.

I need to `performSegue(withIdentifier:` when user login.

I added this code:

```
override func login(email: String, password: String) {
        // Handle login via your API
        print("Login with: email =\(email) password = \(password)")
        
        dataManager.login(email: email, password: "123456") { (response, error) in
            if let error = error {
                print(error)
            } else if let response = response {
                print("response \(response.count)")
                DispatchQueue.main.async {
                    self.performSegue(withIdentifier: "toMainVC", sender: nil)
                }
            }
        }
    }
```

I got this error:

`Value of type 'LoginCoordinator' has no member 'performSegue'`

Could you please guide me how to solve it?

Thanks.

**Comment by danlozano** [comment]
Hi!

Only ViewControllers which are part of a Storyboard can use the 'performSegue' method.

If you want to handle navigation inside the Coordinator you must find another way to present the controller you want.

Or you can have a delegate which your view controller conforms to, and the Coordinator just calls it's delegate when the login is successfull, and the delegate view controller handles the next step.
