### ISSUE TITLE
Validator Pod Errors

### ISSUE THREAD

**Issue by mcg95** [IcaliaLabs/LoginKit#25]
I am getting errors from the Validator pod which have been since resolved in the original project. Is it possible to update the Validator pod used in this framework to the latest? Thanks.

**Comment by danlozano** [comment]
Sure, will do tonight as soon as possible. 

Thanks for letting me know!

**Comment by mcg95** [comment]
No worries. Thanks for the framework. :D

**Comment by danlozano** [comment]
Thank's for using it!

Update `1.0.1` should be out now. Let me know if everything works ok 👍

**Comment by danlozano** [comment]
Updated Validator to the latest version

**Comment by mcg95** [comment]
It works. Thanks. :)
