### ISSUE TITLE
Three classes not conforming to protocol ValidatableInterfaceElement

### ISSUE THREAD

**Issue by bogdanh** [IcaliaLabs/LoginKit#28]
Hi,

I've tried using your LoginKit but apparently after adding it using cocoapods I'm getting the following errors:

Type 'UISlider' does not conform to protocol 'ValidatableInterfaceElement' (UISlider+Validator.swift)
Type 'UITextField' does not conform to protocol 'ValidatableInterfaceElement' (UITextField+Validator.swift)
Type 'UITextView' does not conform to protocol 'ValidatableInterfaceElement' (UITextView+Validator.swift)

All these appear inside Validator pod, which I think is a dependency pod for your LoginKit.

Please advise which should I do to get rid fo the errors.

Thank you,
Bogdan H.

**Comment by jacobokoenig** [comment]
+1. Any solutions yet?

**Comment by bogdanh** [comment]
Hi @jacobo360,

If I remember well I had to run a 'pod update' afterwards. And that fixed the problem.

Regards.
