### ISSUE TITLE
remove animation in first screen

### ISSUE THREAD

**Issue by SirComet** [IcaliaLabs/LoginKit#3]
how can I remove the animation of the first screen when it appears?

**Comment by danlozano** [comment]
You mean the animation/transition when you go from the initial screen to the login/signup screen?

That's not a feature that exists yet but I'd be happy to add it to the next release I'll be working on over the weekend.

**Comment by SirComet** [comment]
Thank you... It would be awesome.

**Comment by QuynhNguyen** [comment]
Did a pull request for this

**Comment by dcortright** [comment]
Any word on the pull request for this? I think this feature would make for a sleeker transition into the login page if it has the same background image as the splash screen.

**Comment by kurenn** [comment]
@danlozano any word on this?

**Comment by danlozano** [comment]
Added in master branch. Will release new version with that and some other fixes.
