### ISSUE TITLE
Hide Facebook Login button?

### ISSUE THREAD

**Issue by autumnesponda** [IcaliaLabs/LoginKit#32]
I've set shouldShowFacebookButton to false, but the button still appears. Is the Facebook sign in button required?

**Comment by tsanjoto** [comment]
add loginCoordinator.configureAppearance() before loginCoordinator.start()
that works for me

**Comment by danlozano** [comment]
Yeah that sounds right @tsanjoto 

Will refactor this for next release as it seems to be causing problems with many people.
