### ISSUE TITLE
Blank page with only FB button

### ISSUE THREAD

**Issue by croossin** [IcaliaLabs/LoginKit#5]
When it gets presented... it only comes with the facebook button... this is with the exact sample code provided in the example project.
![simulator screen shot apr 21 2017 10 46 46 am](https://cloud.githubusercontent.com/assets/7241069/25289785/edd89362-267f-11e7-96e5-0a1891e0e5fe.png)

**Comment by danlozano** [comment]
Is this in the sample project? 

Or in your own project? If so, could I see your code?

Thanks!
