### ISSUE TITLE
callback methods has empty parameters

### ISSUE THREAD

**Issue by sale7nsr** [IcaliaLabs/LoginKit#6]
the parameters ex. (email,password,..etc) didn't pass parameters "empty"

**Comment by danlozano** [comment]
Weird. 

Will look into this over the weekend.

**Comment by danlozano** [comment]
<img width="956" alt="screen shot 2017-08-27 at 6 21 36 pm" src="https://user-images.githubusercontent.com/2406956/29754908-9fc17556-8b54-11e7-9b56-48a69d5dc7c2.png">

Sample project does not seem to have an issue.

Please re-open if you have any more info or sample code as to when this issue happens.

Thanks!
