### ISSUE TITLE
more customization and support for ios11

### ISSUE THREAD

**Issue by levinli303** [IcaliaLabs/LoginKit#9]
hmmm like you can choose whether facebook login is enabled, and rules to validate the username/password?

and there has been a change in api of CGFont
public /*not inherited*/ init?(_ provider: CGDataProvider)
returns an optional in ios11 sdk now

**Comment by danlozano** [comment]
Yes, will look into this for the next version. Adding more customization is definitely the way I want to go.

Any more ideas welcome.

I think the CGFont has been changed back to NOT using optional in the newest beta.

Thanks!
